### ISSUE TITLE
`num2cn(1) ` raises `IndexError`

### ISSUE THREAD

**Issue by lgc2333** [zeicold/pycnnum#7]
```py
>>> num2cn(1) 
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Coding\python\nb2-workspace\.venv\lib\site-packages\pycnnum\pycnnum.py", line 722, in num2cn
    if (getattr(result_symbols[0], "int_value", None) == 1) and (getattr(result_symbols[1], "power", None) == 1):
IndexError: list index out of range
```

**Comment by zeicold** [comment]
不好意思现在才回你消息. 我打算过节期间好好整整这个包.

**Comment by zeicold** [comment]
Fixed in the coming release
